### ISSUE TITLE
{"error": "RESTRequestHandler instance has no attribute 'say'"}

### ISSUE THREAD

**Issue by vetsolution** [alexylem/jarvis-api#13]
Bonjour, 

J'esaye d'utiliser votre API mais lorsque je lance le code de test (http://127.0.0.1:8082/?say=Hello%20World) ou n'import quelle commandes j'ai ce message d'erreur  " {"error": "RESTRequestHandler instance has no attribute 'say'"}  "

Il semblerai que l’exception se lance a la ligne 111 du fichier server.py

Auriez-vous une idée du problème?

**Comment by Oliv4945** [comment]
Même type d'erreur [ici](https://github.com/Oliv4945/jarvis-android-app/issues/9#issuecomment-297397216) relevé par @jean-luc18.
Comportement changé dans la journée, donc ça vient certainement d'un des deux commit du jour
>http://IP:PORT/?order=test => {"error": "RESTRequestHandler instance has no attribute 'handle_order'"}

**Comment by alexylem** [comment]
C'est corrigé dans la minute... j'ai mergé un pull request de @QuentinCG  sans tester désolé 😄

**Comment by alexylem** [comment]
Voila c'est corrigé. Mettez à jour:
```shell
$> ./jarvis.sh -u
```

**Comment by QuentinCG** [comment]
Sorry :(

**Comment by alexylem** [comment]
Pas de soucy @QuentinCG ca arrive, heureusement que vous êtes la pour continuer à faire évoluer Jarvis!
