### ISSUE TITLE
Retour en erreur sur certaines commandes.

### ISSUE THREAD

**Issue by SebastienVProject** [alexylem/jarvis-api#16]
Salut Alex,
Je fais des tests dans le cadre de l'appli iOS, et en voulant tester avec le plugin jarvis-lemonde, je rencontre le problème suivant:

Requête passée en entrée de l'API jarvis:
`http://192.168.0.14:8080/?order=%22actualités%20de%20la%20rubrique%20politique%22`

Retour: 
`{"error": "No JSON object could be decoded"}`

J'ai comme l'impression que l'API n'aime pas certains retours.

Par contre, si je passe l'ordre suivant (même plugin):
`http://192.168.0.14:8080/?order=%22liste%20des%20rubriques `

le retour est ok pour moi au niveau de l'appli
`[{"answer": "Il y \u00e0 12 rubriques : international, politique, soci\u00e9t\u00e9, \u00e9conomique, culture, id\u00e9es, plan\u00e8te, sport, sciences, pixels, campus, le mag."}]`

J'aimerais donc avoir ton avis sur ça. Problème au niveau de l'API, ou du plugin?
Seb

**Comment by SebastienVProject** [comment]
Lorsque je ne passe pas par l'API, et que tape directement l'ordre dans jarvis:
```
jarvis -x "actualité de la rubrique politique"
Traceback (most recent call last):
  File "/Users/utilisateur/jarvis/plugins_installed/jarvis-leMonde/python/news.py", line 3, in <module>
    import lxml.html
ImportError: No module named lxml.html
```
Donc il y a plutôt un souci avec le plugin, ou du moins mon installation (je suis passé par le menu Jarvis pour procéder à l'installation)

**Comment by SebastienVProject** [comment]
Quelque soit la source de l'erreur finalement, afin de fiabiliser le retour au niveau de l'API, il faudrait que l'API retourne toujours un même type de réponse idéalement, à savoir un tableau de json.

dans le cas de mon erreur décrite précédemment, il serait donc peut être préférable de récupérer:
`[{"error": "No JSON object could be decoded"}]`

Je te laisse voir ce qu'il est préférable de faire. Sinon, je devrais gérer le fait qu'on n'a pas systématiquement un tableau en retour.

**Comment by SebastienVProject** [comment]
L'impact sur l'API pouvant être sensible (en fonction de qui la consomme aujourd'hui), j'ai ajouté au niveau de l'application iOS la gestion des cas suivants:
- si l'api retourne un tableau vide, alors affichage du message "aucune information a été retournée par openjarvis"
- si l'api ne retourne pas un tableau (directement un son), j'affiche le contenu de la balise "error"

**Comment by alexylem** [comment]
@SebastienVProject salut et désolé pour ma réponse tardive.
Je ne peux pas contrôler la sortie des plugins tiers, s'ils affichent n'importe quoi sans utiliser les fonctions d'affichage / parole, alors tu risques de te retrouver avec n'importe quoi dans le JSON, voir un format incorrect.
Je pense que ton approche est la bonne, dis moi si tu as besoin d'autre chose ou de changement sur l'API.
