### ISSUE TITLE
Commande imbriquées suite a requete JSON

### ISSUE THREAD

**Issue by jessux** [alexylem/jarvis-api#2]
Bonjour,

J'aimerais que lorsque l'on envoi une requête JSON à jarvis qui contient un ordre qui correspond à une requête imbriquée qu'il soit possible d’interagir après en mode clavier

ex : 
```
    MUSIQUE==say "Voulez-vous un peux de musique ?"
    >OUI==(lance la musique)
    >NON==say "Ok va pour le silence"
```

Merci

**Comment by alexylem** [comment]
Quand tu dis en mode clavier, j'imagine que c'est via l'API? Comment pourrait-il y avoir dans la même conversation des interactions via l'API, et via le clavier/voix?
Juste pour être sûr, on parle bien de pouvoir entretenir des conversations (commandes imbriquées) du début à la fin depuis l'API en JSON? comme ceci:

``` shell
$> curl -d '{"order":"musique"}' http://127.0.0.1:8080 
{"hestia":"Voulez-vous un peux de musique ?"}]
$> curl -d '{"order":"oui"}' http://127.0.0.1:8080 
{"hestia":"Ok"}]
```

**Comment by jessux** [comment]
Le mieux pour moi serait de lancer la commande curl et de pouvoir repondre par oui avec le micro

**Comment by alexylem** [comment]
Tu pourrais m'expliquer quel est ton objectif?
Parce que tu pourrais simplement (à tester):

``` shell
$> ./jarvis.sh -x "musique"
```

Et si tu veux absolument la sortie en JSON

``` shell
$> ./jarvis.sh -jx "musique"
```

Merci :smile:

**Comment by jessux** [comment]
Bonjour, 

Désolé pour ma réponse tardive

Mon objectif est de développer une application qui fait de l'analyse comportementale et qui lorsqu'il détecte un éventement (suite de triggers) envoie a jarvis une requête JSON pour qu'il pose la question à l'utilisateur et que en fonction de la réponse de l'utilisateur améliore au fur et à mesure la compréhension de ses habitudes.

par exemple : 

API :
```
(une personne rentre dans la cuisine)
(il est 8h15)
**détection de l'habitude de lancer un café**
```
API a détécté un habitude et envoi un json a jarvis du type :
```
 {"order":"cafe","question":"voulez-vous un café"}
```

Lorsque jarvis recoit le JSON 

```
JARVIS : Voulez-vous un café ?
(user) : Oui
```

Jarvis renvoie un JSON a mon API
JSON = {"order":"café","response":"oui","datetime":2016-11-23 15:44:00"}

Voilà, j'espère que je suis assez compréhensible :)

**Comment by alexylem** [comment]
Très clair, je comprends le cas d'utilisation.
Donc ce que je vais essayer de faire:
**commands**
```shell
CAFE==say "Voulez-vous un café?"
>*OUI*==say "Ok" && start_coffee.sh
>*NON*==say "Ok"
```
Lorsque Jarvis est lancé avec un ordre:
```shell
$> ./jarvis.sh -x "café"
Jarvis: Voulez-vous un café?
You: # say something
```
Dans ce mode la il faut répondre à l'oral
Pour répondre avec le clavier il faudra utiliser le flag `-k`
```shell
$> ./jarvis.sh -kx "café"
Jarvis: Voulez-vous un café?
You: # type something
```
Si le sortie est en `JSON` (flag `-j`) le programme quittera et il faudra répondre avec l'API (car j'en ai besoin pour l'interface utilisateur)
```shell
$> ./jarvis.sh -jx "café"
[{"Jarvis":"Vous-vous un café?"}]
$> ./jarvis.sh -jx "oui"
[{"Jarvis":"Ok"}]
````
Ca t'irait comme ca?

**Comment by jessux** [comment]
Ce serait parfait :)

**Comment by alexylem** [comment]
Je bosse dessus, ca avance mais ca me force à revoir la structure complète du code et à mettre en place des tests de non-régression automatiques (ce que j'aurais du faire depuis longtemps) donc merci 👍

**Comment by alexylem** [comment]
Voila c'est corrigé. Mettez à jour:
```shell
$> ./jarvis.sh -u
```
