### ISSUE TITLE
Sécurisation de l'API par token

### ISSUE THREAD

**Issue by byackee** [alexylem/jarvis-api#4]
Passer par une api sécurisée. Il faudrait un token généré par le serveur et a mettre dans la commande pour sécuriser les actions de jarvis.
Ceci permettra d'appeler l'API au travers d'internet

**Comment by alexylem** [comment]
Bonne idée, mais déjà discuté ici: #1 
Merci d'y mettre un 👍  afin que je le traite rapidement.
