### ISSUE TITLE
IP is empty: Starting RestAPI server on http://:8080

### ISSUE THREAD

**Issue by Hatto94** [alexylem/jarvis-api#5]
Bonjour,

Je me suis mis récemment a la configuration de Jarvis sur mon Raspberry. 
Le fonctionnement de base est fonctionnel, en voulant aller plus loin en expérimentant avec jarvis-api des soucis commencent à se poser.
Au démarrage de Jarvis, je suis notifié d'un souci au lancement du serveur embarqué :

> Starting RestAPI server on http://:8080
> nohup: redirection de la sortie d'erreur standard vers la sortie standard
> Starting User Interface on http://:8080
> nohup: redirection de la sortie d'erreur standard vers la sortie standard

J'ai regardé un peu la configuration du plugin au cas ou, mais seul le port y est référencé.
C'est curieux que l'adresse IP du raspberry ne soit pas récupérée 

Merci d'avance pour votre retour ;)

**Comment by alexylem** [comment]
>nohup: redirection de la sortie d'erreur standard vers la sortie standard

Ca c'est un autre petit problème que je dois régler. Rien de bloquant pour le fonctionnent de l'API.

>Starting RestAPI server on http://:8080

Etrange en effet. Que se passe-t-il si tu lance dans le terminal:
```shell
ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'
```

A priori c'est juste l'affichage de l'IP qui plante. L'API devrait fonctionner sur l'IP du raspberry pi. L'as-tu testé?

**Comment by Hatto94** [comment]
Bonjour,

En lancant la commande dans Putty cela ne me donne rien visuellement dans le terminal. Ca me permet juste d'écrire une nouvelle commande :

> pi@raspberrypi:~ $ ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'
pi@raspberrypi:~ $

Quand j'ai rencontré le souci pour la première fois, je ne parvenais pas à atteindre le raspberry depuis un navigateur (erreur 404 comme si le serveur n'était pas lancé). Mais cela fonctionne désormais, en appelant simplement :

> http://192.168.0.2:8080/?say=salut

Merci en tout cas pour le rapide retour ;)

**Comment by alexylem** [comment]
Ok donc c'est juste pas partie extraction de l'ip qui ne marche pas. Ca te dérangerait de coller le résultat de `ifconfig` ? (pense à anonymiser ton IP publique si elle s'affiche). Merci!

**Comment by yaazzz** [comment]
eth0      Link encap:Ethernet  HWaddr xx:xx:xx:xx:xx:xx
          adr inet6: xxxx::xxx:xxxx:xxxx:xxxx/64 Scope:Lien
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Boucle locale
          inet adr:127.0.0.1  Masque:255.0.0.0
          adr inet6: ::1/128 Scope:Hôte
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr xx:xx:xx:xx:xx:xx
          inet adr:xxx.xxx.xxx.xxx  Bcast:xxx.xxx.xxx.xxx  Masque:255.255.255.0
          adr inet6: xxxx::xxx:xxxx:xxxx:xxxx/64 Scope:Lien
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5450 errors:0 dropped:307 overruns:0 frame:0
          TX packets:2775 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1000
          RX bytes:454235 (443.5 KiB)  TX bytes:1207345 (1.1 MiB)

**Comment by alexylem** [comment]
Ok on dirait que le problème est que ton Linux est en français. Donc c'est écrit `adr` au lieu de `addr`.
Tu peux tester ca?
```
ifconfig | sed -En 's/127.0.0.1//;s/.*inet (ad[d]?r:)?(([0-9]*\.){3}[0-9]*).*/\2/p'
```

**Comment by yaazzz** [comment]
ifconfig | sed -En 's/127.0.0.1//;s/.*inet (ad[d]?r:)?(([0-9]*\.){3}[0-9]*).*/\2/p'
me revoie bien mon ip.

J'ai modifié les fichiers functions.sh dans jeedom_api et jeedom_ui et tout est ok.

Problème résolu. Merci pour ta réactivité.

**Comment by alexylem** [comment]
Ne change surtout pas les fichiers du plugins, ca va bloquer les mises à jour. Je fais la correction moi (de suite)
Pour écraser tes changements locaux:
```
cd plugins/jarvis-ui/
git reset --hard
```

**Comment by yaazzz** [comment]
Mise à jour faite en lançant les commandes que tu as demandé. Tout est OK. Merci encore.

**Comment by Hatto94** [comment]
C'est ok de mon côté également, l'adresse s'affiche correctement.
Merci pour les mises à jour.
