### ISSUE TITLE
Problème avec Jarvis-API

### ISSUE THREAD

**Issue by azertigrou** [alexylem/jarvis-api#8]
Bonjour,

Chez moi, l'API ne semble pas fonctionner.
Quand je lance Jarvis, le serveur est bien lancé:
Starting RestAPI server on http://192.168.1.102:8082

Et quand je lance une requête:
 curl "http://192.168.1.102:8082?say=Hello World"
<head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 400.
<p>Message: Bad request syntax ('GET /?say=Hello World HTTP/1.1').
<p>Error code explanation: 400 = Bad request syntax or unsupported method.
</body>
Idem avec 
pi@domoticz:~/jarvis$ curl "http://127.0.0.1:8082?say=Hello World"

Idem lorsque je change le port.

**Comment by alexylem** [comment]
Salut @azertigrou 
Bon j'imagine que Jarvis tourne toujours quand tu fais tes requêtes http. Juste au cas ou 😄 
Ca pourrait être un autre programme qui utilise ce port.
Tu peux checker les logs? (le plugin jarvis-api écrit dans le log de Jarvis)
```shell
$> tail jarvis.log
```

**Comment by wikijm** [comment]
Bonjour @alexylem,

Même problème, mais qui semble lié à la présence d'un espace (' ') dans la requête.

Voir https://asciinema.org/a/113341

**Comment by azertigrou** [comment]
Ça a refonctionné après réinstallation de Sarah. Je ne sais pas pourquoi

**Comment by alexylem** [comment]
Idem chez moi, bizarre ça marchait avant...

Il faut encoder l'URL:
```shell
curl "http://192.168.1.102:8082?say=Hello%20World"
```
ou
```shell
curl -G "http://192.168.1.102:8082" --data-urlencode "say=Hello World"
```
il faut que je mette à jour la doc...

**Comment by Oliv4945** [comment]
@alexylem : Sur le téléphone je ne peux pas vérifier si c'est fait exprès mais tu as ajouté un certificat à ce commit.

**Comment by alexylem** [comment]
pas fait exprès je le décochais à chaque fois et la j'ai oublié, la va dégager au prochain commit

**Comment by Oliv4945** [comment]
Ok, me .gitignore est pratique :-)
